getdir: getdir.c
	sudo cp getdir.c /usr/local/src
	sudo gcc -o /usr/local/bin/getdir /usr/local/src/getdir.c


movieWatcher: movieWatcher.c
	gcc -o movieWatcher ini.c movieWatcher.c

socketReader: socketReader.c
	gcc -o socketReader socketReader.c
