#!/bin/bash

if [ $# -lt 1 ]; then
	echo Usage: $BASH_SOURCE target
	exit -1
fi

PYSRC=$(python -c "import os.path; import datetime; print(os.path.dirname(datetime.__file__))")

grep -nr --include "*.py" "$1" $PYSRC 
